- hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        name: "{{ packages }}"
      vars:
        packages:
          - i3
          - xinit
          - build-essential
          - gcc
          - make
          - perl
          - x11-xserver-utils
          - sudo
          - terminator
          - curl
          - dbus-x11
          - open-vm-tools-desktop
          
    - name: install headers
      apt:
        name: linux-headers-amd64
        state: build-dep

    - name: Download code
      get_url:
        url: https://update.code.visualstudio.com/latest/linux-deb-x64/stable
        dest: /root/code.deb

    - name: Install code
      apt:
        deb: /root/code.deb

    - name: Download Chrome
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /root/google-chrome.deb

    - name: Install Chrome
      apt:
        deb: /root/google-chrome.deb

    - name: System configs maxuser
      lineinfile:
        path: /etc/sysctl.conf
        line: fs.inotify.max_user_watches=524288
        
    - name: System configs swap
      lineinfile:
        path: /etc/sysctl.conf
        line: vm.swappiness=10
        
    - name: setup nodejs
      get_url: 
        url: https://deb.nodesource.com/setup_13.x
        dest: /root/setup-node
    
    - name: run nodejs script
      script: /root/setup-node
    
    - name: install nodejs
      apt:
        update_cache: yes
        name: nodejs
      
    - name: monodb key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present
        
    - apt_repository:
        repo: deb http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 main
        state: present

    - name: install mongodb
      apt:
        update_cache: yes
        name: mongodb-org
        
    - name: Start service mongodb
      service:
        name: mongod
        state: started
        enabled: yes
