- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install packages
      apt:
        update_cache: yes
        name: "{{ packages }}"
      vars:
        packages:
          - i3
          - xinit
          - build-essential
          - gcc
          - make
          - perl
          - x11-xserver-utils
          - sudo
          - terminator
          - dbus-x11
          
    - name: install headers
      apt:
        name: linux-headers-amd64
        state: build-dep

    - name: Download Chrome
      get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /root/google-chrome.deb

    - name: Install Chrome
      apt:
        deb: /root/google-chrome.deb
